# Site settings
title:       cascad.io
email:       dave@cascad.io
author:      Dave Smith
description: "A blog about data, the Northwest, and other fun stuff."
baseurl:     ""
url:         "http://cascad.io"

# Google analytics
google_analytics: UA-59916667-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username:
twitter_username: 
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
